### ISSUE TITLE
start button is still visible in win7

### ISSUE THREAD

**Issue by dddreee** [pash2048/taskbar-hider#1]
how to fix it?

**Comment by pash2048** [comment]
@dddreee I have no idea about it and I don't have a win 7 machine to test.
But I try to install and fix it.

**Comment by dddreee** [comment]
> @dddreee I have no idea about it and I don't have a win 7 machine to test. But I try to install and fix it.

Thanks, I used `HideTaskbar.exe` and it worked for me. 😁
